import Header from "@/components/Header";
import GearCard from "@/components/portfolio/GearCard";
import React from "react";

interface ImpactProps {}

const Impact: React.FC<ImpactProps> = ({}) => {
  return (
    <div>
      <Header />
      <div className="flex flex-col impact">
        <div className="top-section">
          <div className="overlay" />
          <div className="top-section-item">
            <div className="top-section-item-title">Impact</div>
            <div className="top-section-item-body">
              Olive Holdings current portfolio companies have already
              established a record of demonstrable results across key areas
              including income generation, disrupting global supply chains and
              empowering women.
            </div>
          </div>
        </div>
        <div className="team-body">
          <div className="team-title">A few key metrics</div>
          <div className="flex flex-row flex-wrap team-images impact-cards">
            <GearCard
              title="3"
              className="impact-right-card"
              body="Portfolio companies the cocoa, shea and citrus sectors"
            />
            <GearCard
              title="2"
              className="impact-right-card"
              body="Major technology innovations developed to strengthen value chain"
            />
            <GearCard
              title="$10M+"
              className="impact-right-card"
              body="Total ARR generated by portfolio companies"
            />
            <GearCard
              title="4"
              className="impact-right-card"
              body="Factories owned by portfolio companies in Ghana, Nigeria &amp; Germany"
            />
            <GearCard
              title="70K+"
              className="impact-right-card"
              body="Female suppliers in our network"
            />
            <GearCard
              title="$5M+"
              className="impact-right-card"
              body="Direct income to local farmers"
            />
          </div>
        </div>

        {/* <Footer /> */}
      </div>
    </div>
  );
};

export default Impact;
